### ISSUE TITLE
Can I build so file?

### ISSUE THREAD

**Issue by Gpwner** [cmeng-git/ffmpeg-android#4]

**Comment by cmeng-git** [comment]
Not sure what is your problem.

If you are referring to jni libraries so files, you can execute the two tasks in the build.gradle. Please note the scripts are designed to run on Linux machine only.

/*
 * The task builds all the 3 static libraries i.e. vpx, openssl and ffmpeg; this need to be
 * executed at least once to generate all the static libraries before the aTalk apk build process.
 */
task getJniLibs(type: org.gradle.api.tasks.Exec) {
    workingDir "${projectDir}/jni/"
    executable './fetch-jnilibs4atalk.sh'
}

/*
 * The task builds all the 3 static libraries i.e. vpx, openssl and ffmpeg; this need to be
 * executed at least once to generate all the static libraries before the aTalk apk build process.
 */
task initJniLibs(type: Exec) {
    workingDir "${projectDir}/jni/static_library_built"
    executable './build-jnilibs4atalk.sh'
 }

**Comment by cmeng-git** [comment]
Please refer to https://github.com/cmeng-git/atalk-android/tree/master/aTalk/jni for the latest
updated scripts and build instructions. This repository is not further maintained since v1.6.8.
